#!/bin/bash
# ==============================================================================
# Start mDNSResponder daemon
# ==============================================================================
echo "[$(date)] INFO: Starting mDNS Responder..."

# Start in debug mode (foreground) as expected by s6-rc
exec /usr/sbin/mdnsd -debug
